blank_issues_enabled: false
contact_links:
  - name: Pukunui Malaysia support
    url: https://pukunui.com/home/location/malaysia/
    about: Contact Pukunui Malaysia about product support.
  - name: Subscription terms and support policy
    url: https://pukunui.com/docs/policy-moodle-marketplace/
    about: Review the Pukunui Plugin Subscription Terms and Support Policy.
